/* GormVersion.h.in
 *
 * This file is automatically generated from the Version file.
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Copyright (C) 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNUstep.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02111 USA.
 */

#ifndef INCLUDED_GormVersion_h
#define INCLUDED_GormVersion_h

#define GORM_MAJOR_VERSION 1
#define GORM_MINOR_VERSION 5
#define GORM_SUBMINOR_VERSION 0

#endif /* INCLUDED_GormVersion_h */
