# Additional include directories the compiler should search
ADDITIONAL_INCLUDE_DIRS += -I../..

ifeq ($(GNUSTEP_TARGET_OS),mingw32)
ADDITIONAL_GUI_LIBS += -lGorm ../../Gorm.app/Gorm.exe.a
endif
ifeq ($(GNUSTEP_TARGET_OS),cygwin)
0Menus_LIBRARIES_DEPEND_UPON += -lGorm
endif
