# Additional include directories the compiler should search
ADDITIONAL_INCLUDE_DIRS += -I../..

ifeq ($(GNUSTEP_TARGET_OS),mingw32)
1Windows_LIBRARIES_DEPEND_UPON += -lGorm     
endif
ifeq ($(GNUSTEP_TARGET_OS),cygwin)
1Windows_LIBRARIES_DEPEND_UPON += -lGorm
endif